# Generated by Django 2.1.15 on 2020-03-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=15)),
                ('mail', models.EmailField(default='email@email.email', max_length=254)),
                ('otp', models.CharField(default=None, max_length=6)),
                ('used', models.BooleanField(default=False)),
                ('eligible_e2e', models.BooleanField(default=False)),
                ('eligible_emi', models.BooleanField(default=False)),
            ],
        ),
    ]
